package ifneeded tkoo 0.2 [list source [file join $dir tkoo-v0.2.tm]]
package ifneeded tkoo::browser 0.2 [list source [file join $dir tkoo browser-v0.2.tm]]
package ifneeded tkoo::button 0.2 [list source [file join $dir tkoo button-v0.2.tm]]
package ifneeded tkoo::canvas 0.2 [list source [file join $dir tkoo canvas-v0.2.tm]]
package ifneeded tkoo::checkbutton 0.2 [list source [file join $dir tkoo checkbutton-v0.2.tm]]
package ifneeded tkoo::combobox 0.2 [list source [file join $dir tkoo combobox-v0.2.tm]]
package ifneeded tkoo::dtree 0.2 [list source [file join $dir tkoo dtree-v0.2.tm]]
package ifneeded tkoo::entry 0.2 [list source [file join $dir tkoo entry-v0.2.tm]]
package ifneeded tkoo::frame 0.2 [list source [file join $dir tkoo frame-v0.2.tm]]
package ifneeded tkoo::labelframe 0.2 [list source [file join $dir tkoo labelframe-v0.2.tm]]
package ifneeded tkoo::label 0.2 [list source [file join $dir tkoo label-v0.2.tm]]
package ifneeded tkoo::listbox 0.2 [list source [file join $dir tkoo listbox-v0.2.tm]]
package ifneeded tkoo::menubutton 0.2 [list source [file join $dir tkoo menubutton-v0.2.tm]]
package ifneeded tkoo::message 0.2 [list source [file join $dir tkoo message-v0.2.tm]]
package ifneeded tkoo::notebook 0.2 [list source [file join $dir tkoo notebook-v0.2.tm]]
package ifneeded tkoo::panedwindow 0.2 [list source [file join $dir tkoo panedwindow-v0.2.tm]]
package ifneeded tkoo::progressbar 0.2 [list source [file join $dir tkoo progressbar-v0.2.tm]]
package ifneeded tkoo::radiobutton 0.2 [list source [file join $dir tkoo radiobutton-v0.2.tm]]
package ifneeded tkoo::scale 0.2 [list source [file join $dir tkoo scale-v0.2.tm]]
package ifneeded tkoo::scrollbar 0.2 [list source [file join $dir tkoo scrollbar-v0.2.tm]]
package ifneeded tkoo::scrolledframe 0.2 [list source [file join $dir tkoo scrolledframe-v0.2.tm]]
package ifneeded tkoo::separator 0.2 [list source [file join $dir tkoo separator-v0.2.tm]]
package ifneeded tkoo::sizegrip 0.2 [list source [file join $dir tkoo sizegrip-v0.2.tm]]
package ifneeded tkoo::spinbox 0.2 [list source [file join $dir tkoo spinbox-v0.2.tm]]
package ifneeded tkoo::text 0.2 [list source [file join $dir tkoo text-v0.2.tm]]
package ifneeded tkoo::treeview 0.2 [list source [file join $dir tkoo treeview-v0.2.tm]]
package ifneeded tkoo::widgets 0.2 [list source [file join $dir tkoo widgets-v0.2.tm]]
package ifneeded tkoo::mixin::help 0.2 [list source [file join $dir tkoo mixin help-v0.2.tm]]
